#ifndef ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_ENUMS_ENCOUNTER_CHARACTER_H_
#define ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_ENUMS_ENCOUNTER_CHARACTER_H_

namespace game::enums {

enum EncounterCharacter {
  Fry, Leela, Bender
};

}

#endif //ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_ENUMS_ENCOUNTER_CHARACTER_H_
