#ifndef ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_SECTORS_SECTOR_OBJECT_TYPE_H_
#define ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_SECTORS_SECTOR_OBJECT_TYPE_H_

namespace game::enums {
  enum SectorObjectType {
    Asteroid, Planet, Encounter, EmptySpace, Spaceship
  };
}

#endif //ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_SECTORS_SECTOR_OBJECT_TYPE_H_
