#ifndef ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_UI_ANSI_COLORS_H_
#define ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_UI_ANSI_COLORS_H_

namespace engine::ui {

#define ANSI_COLOR_RED "\x1b[31m"
#define ANSI_COLOR_GREEN "\x1b[32m"
#define ANSI_COLOR_YELLOW "\x1b[33m"
#define ANSI_COLOR_BLUE "\x1b[34m"
#define ANSI_COLOR_RESET "\x1b[0m"

}

#endif //ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_UI_ANSI_COLORS_H_
