#ifndef ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_DATA_MODELS_CONSEQUENCE_SOURCE_H_
#define ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_DATA_MODELS_CONSEQUENCE_SOURCE_H_

#include <string>
namespace game {

struct ConsequenceSource {
  std::string source_;
};

}

#endif //ASSESSMENT_CPLUS_23_24_GUNWUNBUN_SRC_GAME_DATA_MODELS_CONSEQUENCE_SOURCE_H_
